/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Activity: { // root type
    date: string; // String!
    id: number; // Int!
    planned: boolean; // Boolean!
  }
  Item: { // root type
    duration: number; // Int!
    id: number; // Int!
    stuff?: string | null; // String
    task: string; // String!
    time: string; // String!
  }
  Leader: { // root type
    id: number; // Int!
    name: string; // String!
  }
  Location: { // root type
    city: string; // String!
    id: number; // Int!
    place?: string | null; // String
  }
  Mutation: {};
  Program: { // root type
    id: number; // Int!
    split: number; // Int!
    title: string; // String!
    year: number; // Int!
  }
  Query: {};
  Step: { // root type
    id: number; // Int!
    name: string; // String!
  }
  Type: { // root type
    id: number; // Int!
    name: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Activity: { // field return type
    chief: NexusGenRootTypes['Leader']; // Leader!
    date: string; // String!
    id: number; // Int!
    items: NexusGenRootTypes['Item'][]; // [Item!]!
    location: NexusGenRootTypes['Location']; // Location!
    planned: boolean; // Boolean!
    program: NexusGenRootTypes['Program']; // Program!
    step: NexusGenRootTypes['Step']; // Step!
    type: NexusGenRootTypes['Type']; // Type!
  }
  Item: { // field return type
    activity: NexusGenRootTypes['Activity']; // Activity!
    duration: number; // Int!
    id: number; // Int!
    stuff: string | null; // String
    task: string; // String!
    time: string; // String!
  }
  Leader: { // field return type
    activities: NexusGenRootTypes['Activity'][]; // [Activity!]!
    id: number; // Int!
    name: string; // String!
  }
  Location: { // field return type
    activities: NexusGenRootTypes['Activity'][]; // [Activity!]!
    city: string; // String!
    id: number; // Int!
    place: string | null; // String
  }
  Mutation: { // field return type
    createActivity: NexusGenRootTypes['Activity']; // Activity!
    createItem: NexusGenRootTypes['Item']; // Item!
    createLeader: NexusGenRootTypes['Leader']; // Leader!
    createLocation: NexusGenRootTypes['Location']; // Location!
    createProgram: NexusGenRootTypes['Program']; // Program!
    createStep: NexusGenRootTypes['Step']; // Step!
    createType: NexusGenRootTypes['Type']; // Type!
    deleteActivity: NexusGenRootTypes['Activity'] | null; // Activity
    deleteItem: NexusGenRootTypes['Item'] | null; // Item
    deleteLeader: NexusGenRootTypes['Leader'] | null; // Leader
    deleteLocation: NexusGenRootTypes['Location'] | null; // Location
    deleteProgram: NexusGenRootTypes['Program'] | null; // Program
    deleteStep: NexusGenRootTypes['Step'] | null; // Step
    deleteType: NexusGenRootTypes['Type'] | null; // Type
    updateActivity: NexusGenRootTypes['Activity'] | null; // Activity
    updateItem: NexusGenRootTypes['Item'] | null; // Item
    updateLeader: NexusGenRootTypes['Leader'] | null; // Leader
    updateLocation: NexusGenRootTypes['Location'] | null; // Location
    updateProgram: NexusGenRootTypes['Program'] | null; // Program
    updateStep: NexusGenRootTypes['Step'] | null; // Step
    updateType: NexusGenRootTypes['Type'] | null; // Type
  }
  Program: { // field return type
    activities: NexusGenRootTypes['Activity'][]; // [Activity!]!
    id: number; // Int!
    split: number; // Int!
    title: string; // String!
    year: number; // Int!
  }
  Query: { // field return type
    activities: NexusGenRootTypes['Activity'][]; // [Activity!]!
    activity: NexusGenRootTypes['Activity']; // Activity!
    item: NexusGenRootTypes['Item']; // Item!
    items: NexusGenRootTypes['Item'][]; // [Item!]!
    leader: NexusGenRootTypes['Leader']; // Leader!
    leaders: NexusGenRootTypes['Leader'][]; // [Leader!]!
    location: NexusGenRootTypes['Location']; // Location!
    locations: NexusGenRootTypes['Location'][]; // [Location!]!
    program: NexusGenRootTypes['Program']; // Program!
    programs: NexusGenRootTypes['Program'][]; // [Program!]!
    step: NexusGenRootTypes['Step']; // Step!
    steps: NexusGenRootTypes['Step'][]; // [Step!]!
    type: NexusGenRootTypes['Type']; // Type!
    types: NexusGenRootTypes['Type'][]; // [Type!]!
  }
  Step: { // field return type
    activities: NexusGenRootTypes['Activity'][]; // [Activity!]!
    id: number; // Int!
    name: string; // String!
  }
  Type: { // field return type
    activities: NexusGenRootTypes['Activity'][]; // [Activity!]!
    id: number; // Int!
    name: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Activity: { // field return type name
    chief: 'Leader'
    date: 'String'
    id: 'Int'
    items: 'Item'
    location: 'Location'
    planned: 'Boolean'
    program: 'Program'
    step: 'Step'
    type: 'Type'
  }
  Item: { // field return type name
    activity: 'Activity'
    duration: 'Int'
    id: 'Int'
    stuff: 'String'
    task: 'String'
    time: 'String'
  }
  Leader: { // field return type name
    activities: 'Activity'
    id: 'Int'
    name: 'String'
  }
  Location: { // field return type name
    activities: 'Activity'
    city: 'String'
    id: 'Int'
    place: 'String'
  }
  Mutation: { // field return type name
    createActivity: 'Activity'
    createItem: 'Item'
    createLeader: 'Leader'
    createLocation: 'Location'
    createProgram: 'Program'
    createStep: 'Step'
    createType: 'Type'
    deleteActivity: 'Activity'
    deleteItem: 'Item'
    deleteLeader: 'Leader'
    deleteLocation: 'Location'
    deleteProgram: 'Program'
    deleteStep: 'Step'
    deleteType: 'Type'
    updateActivity: 'Activity'
    updateItem: 'Item'
    updateLeader: 'Leader'
    updateLocation: 'Location'
    updateProgram: 'Program'
    updateStep: 'Step'
    updateType: 'Type'
  }
  Program: { // field return type name
    activities: 'Activity'
    id: 'Int'
    split: 'Int'
    title: 'String'
    year: 'Int'
  }
  Query: { // field return type name
    activities: 'Activity'
    activity: 'Activity'
    item: 'Item'
    items: 'Item'
    leader: 'Leader'
    leaders: 'Leader'
    location: 'Location'
    locations: 'Location'
    program: 'Program'
    programs: 'Program'
    step: 'Step'
    steps: 'Step'
    type: 'Type'
    types: 'Type'
  }
  Step: { // field return type name
    activities: 'Activity'
    id: 'Int'
    name: 'String'
  }
  Type: { // field return type name
    activities: 'Activity'
    id: 'Int'
    name: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createActivity: { // args
      chief: number; // Int!
      date: string; // String!
      location: number; // Int!
      planned: boolean; // Boolean!
      program: number; // Int!
      step: number; // Int!
      type: number; // Int!
    }
    createItem: { // args
      activity: number; // Int!
      duration: number; // Int!
      stuff?: string | null; // String
      task: string; // String!
      time: string; // String!
    }
    createLeader: { // args
      name: string; // String!
    }
    createLocation: { // args
      city: string; // String!
      place?: string | null; // String
    }
    createProgram: { // args
      split: number; // Int!
      title: string; // String!
      year: number; // Int!
    }
    createStep: { // args
      name: string; // String!
    }
    createType: { // args
      name: string; // String!
    }
    deleteActivity: { // args
      id: number; // Int!
    }
    deleteItem: { // args
      id: number; // Int!
    }
    deleteLeader: { // args
      id: number; // Int!
    }
    deleteLocation: { // args
      id: number; // Int!
    }
    deleteProgram: { // args
      id: number; // Int!
    }
    deleteStep: { // args
      id: number; // Int!
    }
    deleteType: { // args
      id: number; // Int!
    }
    updateActivity: { // args
      chief?: number | null; // Int
      date?: string | null; // String
      id: number; // Int!
      location?: number | null; // Int
      planned?: boolean | null; // Boolean
      program?: number | null; // Int
      step?: number | null; // Int
      type?: number | null; // Int
    }
    updateItem: { // args
      activity?: number | null; // Int
      duration?: number | null; // Int
      id: number; // Int!
      stuff?: string | null; // String
      task?: string | null; // String
      time?: string | null; // String
    }
    updateLeader: { // args
      id: number; // Int!
      name?: string | null; // String
    }
    updateLocation: { // args
      city?: string | null; // String
      id: number; // Int!
      place?: string | null; // String
    }
    updateProgram: { // args
      id: number; // Int!
      split?: number | null; // Int
      title?: string | null; // String
      year?: number | null; // Int
    }
    updateStep: { // args
      id: number; // Int!
      name?: string | null; // String
    }
    updateType: { // args
      id: number; // Int!
      name?: string | null; // String
    }
  }
  Query: {
    activities: { // args
      program?: number | null; // Int
    }
    activity: { // args
      id: number; // Int!
    }
    item: { // args
      id: number; // Int!
    }
    items: { // args
      activity?: number | null; // Int
    }
    leader: { // args
      id: number; // Int!
    }
    location: { // args
      id: number; // Int!
    }
    program: { // args
      id: number; // Int!
    }
    step: { // args
      id: number; // Int!
    }
    type: { // args
      id: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}